baseURL = "https://gsquire.github.io/static/"
languageCode = "en-us"
title = "Garrett's Blog"
theme = "ezhil"

pygmentsstyle = "perldoc"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 3
summaryLength = 20

[params]
subtitle = "A place for my thoughts on software development"
featherIconsCDN = true
mode = "auto"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/gsquire"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/garrettsquire"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:mail@garrettsquire.com"
